package lecture04;

import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.control.Button;

/**
 * Lecture 4: <code>DataEntryController</code> class implements a controller.
 * 
 * @author Denis Gracanin
 * @version 1
 */
public class DataEntryController implements EventHandler<ActionEvent>  {
	DataEntryModel model = null;
	DataEntryView view = null;
	
	/**
	 * Creates a controller object.
	 * 
	 * @param m The model object.
	 * @param v The view object.
	 */
	public DataEntryController(DataEntryModel m, DataEntryView v) {
		model = m;
		view = v;
		v.addMyHandler(this);
	}

	/**
	 * Handles the action (button) events generated by the view object.
	 * 
	 * @param event The event object.
	 */
	@Override
	public void handle(ActionEvent event) {
		switch(((Button) event.getSource()).getId()) {
		case "UPDATE":
			model.setFirstName(view.getFirstName());
			model.setLastName(view.getLastName());
			model.setGender(view.getGender());
			model.setProgrammingSkills(view.getProgrammingSkills());
			model.setGpa(view.getGpa());
			model.setComment(view.getComment());
			System.out.println(model);
			break;
		case "REVERT":
			view.setFirstName(model.getFirstName());
			view.setLastName(model.getLastName());
			view.setGender(model.getGender());
			view.setProgrammingSkills(model.getProgrammingSkills());
			view.setGpa(model.getGpa());
			view.setComment(model.getComment());
			break;
		case "CLEAR":
			view.clear();
			break;
		default:
		}
	}

}
