
compile: prob4_6.c prob4_2.c prob4_2_g.c
	gcc -lm -pthread -Wall -Werror -o prob4_6 prob4_6.c
	gcc -pthread -Wall -Werror -o prob4_2 prob4_2.c
	gcc -pthread -Wall -Werror -o prob4_2_g prob4_2_g.c

run:
	./prob4_6 1 10 >> output.txt
	./prob4_6 1 12 >> output.txt
	./prob4_6 1 14 >> output.txt
	./prob4_6 1 16 >> output.txt
	./prob4_6 1 18 >> output.txt
	@echo "check"
	./prob4_6 1 20 >> output.txt
	./prob4_6 1 22 >> output.txt
	./prob4_6 1 24 >> output.txt
	./prob4_6 1 26 >> output.txt
	./prob4_6 1 28 >> output.txt
	./prob4_6 1 30 >> output.txt
	@echo "check"
	./prob4_6 2 10 >> output.txt
	./prob4_6 2 12 >> output.txt
	./prob4_6 2 14 >> output.txt
	./prob4_6 2 16 >> output.txt
	./prob4_6 2 18 >> output.txt
	@echo "check"
	./prob4_6 2 20 >> output.txt
	./prob4_6 2 22 >> output.txt
	./prob4_6 2 24 >> output.txt
	./prob4_6 2 26 >> output.txt
	./prob4_6 2 28 >> output.txt
	./prob4_6 2 30 >> output.txt

run2:
	./prob4_2 	1 < sample_data/test5.txt > output.txt
	./prob4_2_g 1 < sample_data/test5.txt >> output.txt
	./prob4_2 	1 < sample_data/test6.txt >> output.txt
	./prob4_2_g 1 < sample_data/test6.txt >> output.txt
	./prob4_2 	1 < sample_data/test7.txt >> output.txt
	./prob4_2_g 1 < sample_data/test7.txt >> output.txt

	./prob4_2 	2 < sample_data/test5.txt >> output.txt
	./prob4_2_g 2 < sample_data/test5.txt >> output.txt
	./prob4_2 	2 < sample_data/test6.txt >> output.txt
	./prob4_2_g 2 < sample_data/test6.txt >> output.txt
	./prob4_2 	2 < sample_data/test7.txt >> output.txt
	./prob4_2_g 2 < sample_data/test7.txt >> output.txt

	./prob4_2 	4 < sample_data/test5.txt >> output.txt
	./prob4_2_g 4 < sample_data/test5.txt >> output.txt
	./prob4_2 	4 < sample_data/test6.txt >> output.txt
	./prob4_2_g 4 < sample_data/test6.txt >> output.txt
	./prob4_2 	4 < sample_data/test7.txt >> output.txt
	./prob4_2_g 4 < sample_data/test7.txt >> output.txt

	./prob4_2 	8 < sample_data/test5.txt >> output.txt
	./prob4_2_g 8 < sample_data/test5.txt >> output.txt
	./prob4_2 	8 < sample_data/test6.txt >> output.txt
	./prob4_2_g 8 < sample_data/test6.txt >> output.txt
	./prob4_2 	8 < sample_data/test7.txt >> output.txt
	./prob4_2_g 8 < sample_data/test7.txt >> output.txt

	./prob4_2 	16 < sample_data/test5.txt >> output.txt
	./prob4_2_g 16 < sample_data/test5.txt >> output.txt
	./prob4_2 	16 < sample_data/test6.txt >> output.txt
	./prob4_2_g 16 < sample_data/test6.txt >> output.txt
	./prob4_2 	16 < sample_data/test7.txt >> output.txt
	./prob4_2_g 16 < sample_data/test7.txt >> output.txt